### ISSUE TITLE
Question regarding syntax

### ISSUE THREAD

**Issue by algebraic-dev** [barelyhuman/resume-lang#1]
You really need something like `endsection`? Why not just `end`?

**Comment by barelyhuman** [comment]
there's 2 reasons or more like 2 blockers. 

1. If i was to use a keyword like `end` then it might very well be a part of the description that you write and so we'd have to introduce a way to separate text from the keywords. This would involve defining all strings in double / single quotes. 
2. I wish to add markdown as valid syntax when using the `text` modifier which would then have conflicts with the above mentioned quotes and would need me to add hacky workarounds in the code. 

`endsection` is my current middle ground to avoid the above 2. 

Another option is that we can have the indents define the scope and then I might not even need the `end<keyword>` parsing and the nesting would be similar to python. 

That is something I'm still considering

**Comment by algebraic-dev** [comment]
Ok! :) Thanks for answering.
